# Generated by Django 5.0.7 on 2024-09-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField()),
                ('estado', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada'), ('ongoing', 'En proceso')], default='abierta', max_length=20)),
                ('jornada', models.CharField(choices=[('fullTime', 'Tiempo completo'), ('halfTime', 'Medio tiempo')], max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
